
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Conversation
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Conversation()
    {

        this.Childrens = new HashSet<Conversation>();

    }


    public System.Guid Id { get; set; }

    public string Content { get; set; }

    public System.Guid OwnerId { get; set; }

    public System.Guid SenderId { get; set; }

    public Nullable<System.Guid> ParentId { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<bool> Status { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Conversation> Childrens { get; set; }

    public virtual Conversation Parent { get; set; }

    public virtual Supplier Owner { get; set; }

    public virtual Supplier Sender { get; set; }

}

}
