
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    public int Id { get; set; }

    public string CompanyName { get; set; }

    public string CompanyAddress { get; set; }

    public string Telephone { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordSalt { get; set; }

    public System.DateTime DateCreated { get; set; }

    public bool IsActive { get; set; }

    public bool IsVerify { get; set; }

}

}
