
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Recruitment
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Recruitment()
    {

        this.Benefits = new HashSet<Benefit>();

        this.Candidates = new HashSet<Candidate>();

        this.JobSkills = new HashSet<JobSkill>();

    }


    public int Id { get; set; }

    public string JobTitle { get; set; }

    public string JobDescription { get; set; }

    public string JobRequirement { get; set; }

    public string Salary { get; set; }

    public System.DateTime DatePosted { get; set; }

    public Nullable<System.DateTime> DateExpired { get; set; }

    public bool IsActive { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Benefit> Benefits { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Candidate> Candidates { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<JobSkill> JobSkills { get; set; }

}

}
