
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class SuplierReport
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string SecretCode { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string TitleReport { get; set; }

    public string ContentReport { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

}

}
