
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Supplier
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Supplier()
    {

        this.Conversations = new HashSet<Conversation>();

        this.Senders = new HashSet<Conversation>();

        this.SupplierCertificates = new HashSet<SupplierCertificate>();

    }


    public System.Guid Id { get; set; }

    public string NameCompany { get; set; }

    public System.DateTime DayoIncor { get; set; }

    public string Representative { get; set; }

    public string MainProduct { get; set; }

    public string MainCustomer { get; set; }

    public string Contact { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Conversation> Conversations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Conversation> Senders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SupplierCertificate> SupplierCertificates { get; set; }

    public virtual SupplierUser SupplierUser { get; set; }

}

}
