
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class UserLogin
{

    public int Id { get; set; }

    public string UserName { get; set; }

    public int RoleId { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public bool IsActive { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordSalt { get; set; }



    public virtual Role Role { get; set; }

}

}
